Revert of Mojo C++ bindings: make ipc/ mojom targets to use STL string/vector types (patchset #3 id:40001 of https://codereview.chromium.org/2181443002/ )
Reason for revert:
This patch has broken compiling on the MSan bots.

Due to memory waterfall shenanigans I haven't had time to investigate why, but I do know that locally reverting this change fixed compile.

Sample failure output:
FAILED: obj/mojo/public/interfaces/bindings/tests/test_interfaces_blink_cpp_sources/test_structs.mojom-blink.o
/b/c/cipd/goma/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/mojo/public/interfaces/bindings/tests/test_interfaces_blink_cpp_sources/test_structs.mojom-blink.o.d -DV8_DEPRECATION_WARNINGS -DENABLE_MDNS=1 -DENABLE_NOTIFICATIONS -DENABLE_PEPPER_CDMS -DENABLE_PLUGINS=1 -DENABLE_PDF=1 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DUSE_UDEV -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_CLIPBOARD_AURAX11=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DNO_TCMALLOC -DMEMORY_TOOL_REPLACES_ALLOCATOR -DMEMORY_SANITIZER_INITIAL_SIZE -DMEMORY_SANITIZER -DENABLE_WEBRTC=1 -DENABLE_EXTENSIONS=1 -DENABLE_TASK_MANAGER=1 -DENABLE_THEMES=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_SERVICE_DISCOVERY=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DENABLE_MEDIA_ROUTER=1 -DFIELDTRIAL_TESTING_ENABLED -DCR_CLANG_REVISION=274369-1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DENABLE_LAYOUT_UNIT_IN_INLINE_BOXES=0 -DENABLE_OILPAN=1 -DWTF_USE_CONCATENATED_IMPULSE_RESPONSES=1 -DWTF_USE_ICCJPEG=1 -DWTF_USE_QCMSLIB=1 -DWTF_USE_WEBAUDIO_FFMPEG=1 -DWTF_USE_DEFAULT_RENDER_THEME=1 -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DU_NOEXCEPT= -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -I../.. -Igen -I../../build/linux/debian_wheezy_amd64-sysroot/usr/include/glib-2.0 -I../../build/linux/debian_wheezy_amd64-sysroot/usr/lib/x86_64-linux-gnu/glib-2.0/include -I../../third_party/WebKit/Source -I../../third_party/WebKit -Igen/blink -Igen/third_party/WebKit -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pipe -B../../third_party/binutils/Linux_x64/Release/bin -fcolor-diagnostics -fdebug-prefix-map=/mnt/data/b/c/b/Chromium_Linux_MSan_Builder/src=. -pthread -m64 -march=x86-64 -Wall -Werror -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-deprecated-register -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-shift-negative-value -Wno-undefined-var-template -Wno-nonportable-include-path -O2 -fno-ident -fdata-sections -ffunction-sections -g1 --sysroot=../../build/linux/debian_wheezy_amd64-sysroot -gline-tables-only -fno-omit-frame-pointer -fsanitize=memory -fsanitize-memory-track-origins=2 -fsanitize-blacklist=../../tools/msan/blacklist.txt -fvisibility=hidden -Xclang -load -Xclang ../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-templates -Xclang -plugin-arg-find-bad-constructs -Xclang follow-macro-expansion -Xclang -plugin-arg-find-bad-constructs -Xclang check-implicit-copy-ctors -Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc -Wheader-hygiene -Wstring-conversion -Xclang -load -Xclang ../../third_party/llvm-build/Release+Asserts/lib/libBlinkGCPlugin.so -Xclang -add-plugin -Xclang blink-gc-plugin -fno-threadsafe-statics -fvisibility-inlines-hidden -std=gnu++11 -fno-rtti -nostdinc++ -isystem../../buildtools/third_party/libc++/trunk/include -isystem../../buildtools/third_party/libc++abi/trunk/include -fno-exceptions -c gen/mojo/public/interfaces/bindings/tests/test_structs.mojom-blink.cc -o obj/mojo/public/interfaces/bindings/tests/test_interfaces_blink_cpp_sources/test_structs.mojom-blink.o
In file included from gen/mojo/public/interfaces/bindings/tests/test_structs.mojom-blink.cc:15:
In file included from gen/mojo/public/interfaces/bindings/tests/test_structs.mojom-blink.h:37:
In file included from gen/mojo/public/interfaces/bindings/tests/rect.mojom-blink.h:37:
In file included from ../../mojo/public/cpp/bindings/wtf_array.h:15:
In file included from ../../mojo/public/cpp/bindings/lib/wtf_clone_equals_util.h:13:
../../third_party/WebKit/Source/wtf/Vector.h:196:32: error: call to deleted constructor of 'mojo::ScopedHandleBase<mojo::Handle>'
            new (NotNull, dst) T(*src);
                               ^ ~~~~
../../third_party/WebKit/Source/wtf/Vector.h:323:62: note: in instantiation of function template specialization 'WTF::VectorCopier<false, mojo::ScopedHandleBase<mojo::Handle> >::uninitializedCopy<mojo::ScopedHandleBase<mojo::Handle> >' requested here
        VectorCopier<VectorTraits<T>::canCopyWithMemcpy, T>::uninitializedCopy(src, srcEnd, dst);
                                                             ^
../../third_party/WebKit/Source/wtf/Vector.h:1004:21: note: in instantiation of member function 'WTF::VectorTypeOperations<mojo::ScopedHandleBase<mojo::Handle> >::uninitializedCopy' requested here
    TypeOperations::uninitializedCopy(other.begin(), other.end(), begin());
                    ^
../../buildtools/third_party/libc++/trunk/include/memory:1740:31: note: in instantiation of member function 'WTF::Vector<mojo::ScopedHandleBase<mojo::Handle>, 0, WTF::PartitionAllocator>::Vector' requested here
            ::new((void*)__p) _Up(_VSTD::forward<_Args>(__args)...);
                              ^
.... snip

TBR=rockot@chromium.org,yzshen@chromium.org
# Not skipping CQ checks because original CL landed more than 1 days ago.
NOPRESUBMIT=true
BUG=624136,631415

Review-Url: https://codereview.chromium.org/2199623002
Cr-Commit-Position: refs/heads/master@{#408913}


CrOS-Libchrome-Original-Commit: 247f0e9a24742981c8fc213f526253fbdef8955f