Revert "Add allow_reentrancy parameter to ObserverList"
This reverts commit 7a30eec9fe13e9f5c91b2373fe96871c1e16ad3c.

Reason for revert: makes compile on WinMSVC64 fail.

FAILED: obj/base/base_unittests/observer_list_unittest.obj 
ninja -t msvc -e environment.x64 -- C:\b\c\goma_client/gomacc.exe <snip> /c ../../base/observer_list_unittest.cc /Foobj/base/base_unittests/observer_list_unittest.obj /Fd"obj/base/base_unittests_cc.pdb"
c:\b\c\b\win\src\base\observer_list_unittest.cc(1269) : error C2220: warning treated as error - no 'object' file generated
c:\b\c\b\win\src\base\observer_list_unittest.cc(1269) : warning C4702: unreachable code

Examples:
https://ci.chromium.org/buildbot/chromium.win/WinMSVC64%20%28dbg%29/3127
https://ci.chromium.org/buildbot/chromium.win/WinMSVC64%20%28dbg%29/3115

The fix should be probably a one-liner while it wasn't too obvious, so let me revert... sorry for that.

Original change's description:
> Add allow_reentrancy parameter to ObserverList
> 
> Certain client code wants to make sure that no loop is
> performed while looping to avoid unexpected behaivor.
> Use this new parameter to check this condition in debug build & unit tests.
> 
> Introduced ReentrantObserverList (which is currently same as defualt)
> to replace the ones that indeed have to be reentrant in a separate CL.
> 
> BUG=812109
> TEST=Covered by unittests
> 
> Change-Id: Idcf2ed59215ad9d3d8da278d15eddfcd2dedffa9
> Reviewed-on: https://chromium-review.googlesource.com/915441
> Commit-Queue: Mitsuru Oshima <oshima@chromium.org>
> Reviewed-by: Daniel Cheng <dcheng@chromium.org>
> Reviewed-by: Wez <wez@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#537949}

TBR=dcheng@chromium.org,oshima@chromium.org,wez@chromium.org

Change-Id: I4a98de69772474f8438087a93a310fa68a88525f
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 812109
Reviewed-on: https://chromium-review.googlesource.com/928061
Reviewed-by: Kinuko Yasuda <kinuko@chromium.org>
Commit-Queue: Kinuko Yasuda <kinuko@chromium.org>
Cr-Commit-Position: refs/heads/master@{#538028}

CrOS-Libchrome-Original-Commit: 6f1f6a67fe0951409e904022e4895a5458fa60b2