Revert of Move ScopedFileDescriptor to dbus/file_descriptor.h (patchset #1 id:1 of https://codereview.chromium.org/1090243003/)
Reason for revert:
Breaks shared_library build with broken exports:

./../dbus/dbus_export.h:20:65: error: ignoring attributes applied to class type 'scoped_ptr<dbus::FileDescriptor, dbus::FileDescriptor::Deleter>' outside of definition [-Werror=attributes]
 #define CHROME_DBUS_EXPORT __attribute__((visibility("default")))
                                                                 ^
../../dbus/file_descriptor.h:81:57: note: in expansion of macro 'CHROME_DBUS_EXPORT'
     scoped_ptr<FileDescriptor, FileDescriptor::Deleter> CHROME_DBUS_EXPORT;

Original issue's description:
> Move ScopedFileDescriptor to dbus/file_descriptor.h
>
> ScopedFileDescriptor was initially introduced to facilitate the
> management of a 'lifeline' FD used when asking permission_broker to
> open a port in the device's firewall on CrOS.  It's actually a scoped
> wrapper around DBus::FileDescriptor, not a platform file descriptor. I
> would like to use it to facilitate some other similar functionality in
> which I create a pipe and pass one end over DBus, so it seems like a
> good idea to move ScopedFileDescriptor into the dbus library directly.
>
> BUG=chromium:481340
> TEST=FirewallHole unit tests still pass
> STATUS=Fixed
> R=keybuk, reillyg, stevenjb
>
> Committed: https://crrev.com/b44fbaabbe9f91e63ad8aa164609a6b31e0de57e
> Cr-Commit-Position: refs/heads/master@{#327089}

TBR=keybuk@chromium.org,reillyg@chromium.org,stevenjb@chromium.org,cmasone@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=chromium:481340

Review URL: https://codereview.chromium.org/1108893003

Cr-Commit-Position: refs/heads/master@{#327103}


CrOS-Libchrome-Original-Commit: ee9dc849ffa2df2820381c31d5ba8200774d287a