Revert 234233 "Add mojo_idl_generator.gypi"
Broke all windows try jobs.

Example:
http://build.chromium.org/p/tryserver.chromium/builders/win/builds/124746

FAILED: E:\b\depot_tools\python_bin\python.exe gyp-win-tool action-wrapper environment.x86 mojom_test_target_Generate_C___source_files_from_mojom_files_ff8ddd79354be39f4d49ff68f7050968.f7de501d36c9a2def832b8cb44ee34af.rsp
Traceback (most recent call last):

  File "../mojo/public/bindings/mojom_bindings_generator.py", line 12, in <module>

    from parser import mojo_parser

ImportError: cannot import name mojo_parser

ninja: build stopped: subcommand failed.


> Add mojo_idl_generator.gypi
> NOT FOR REVIEW
> BUG=
> R=darin@chromium.org
> 
> Review URL: https://codereview.chromium.org/53173008

TBR=davemoore@chromium.org

Review URL: https://codereview.chromium.org/69243003

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@234277 0039d316-1c4b-4281-b951-d872f2087c98


CrOS-Libchrome-Original-Commit: 45c0b6c305703132e804f5b9ee5452efcb2a936c