Mark EventToTypeString with ALLOW_UNUSED to fix the Official gtk build.
It's only used inside an UNSHIPPED_TRACE_EVENT1(), which causes:

../../base/message_loop/message_pump_gtk.cc:17:13: error: unused function 'EventToTypeString' [-Werror,-Wunused-function]

Review URL: https://codereview.chromium.org/131323005

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@244283 0039d316-1c4b-4281-b951-d872f2087c98


CrOS-Libchrome-Original-Commit: fd14f8126d921d85f21960c8a994150343832a57