Revert of Name TaskScheduler's worker threads (patchset #7 id:140001 of https://codereview.chromium.org/1951453002/ )
Reason for revert:
This patch broke the Win x64 build -- The error is
ninja -t msvc -e environment.x64 -- C:\b\build\slave\cache\cipd\goma/gomacc "C:\b\depot_tools\win_toolchain\vs_files\95ddda401ec5678f15eeed01d2bee08fcbc5ee97\VC\bin\amd64\cl.exe" /nologo /showIncludes /FC @obj\base\task_scheduler\base.scheduler_thread_pool_impl.obj.rsp /c ..\..\base\task_scheduler\scheduler_thread_pool_impl.cc /Foobj\base\task_scheduler\base.scheduler_thread_pool_impl.obj /Fdobj\base\base.cc.pdb
c:\b\build\slave\win_x64\build\src\base\task_scheduler\scheduler_thread_pool_impl.cc(515): error C2220: warning treated as error - no 'object' file generated
c:\b\build\slave\win_x64\build\src\base\task_scheduler\scheduler_thread_pool_impl.cc(515): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data

See the whole (broken) compile in https://build.chromium.org/p/chromium/builders/Win%20x64/builds/535/steps/compile/logs/stdio

Original issue's description:
> Name TaskScheduler's worker threads
>
> In conjunction with https://codereview.chromium.org/1937323002/ this
> makes TaskScheduler work with chrome://tracing.
>
> Thread name will be comprised of 3 parts:
>  [1] Thread Pool name, e.g. "TaskSchedulerBackgroudFileIO"
>  [2] "Worker"
>  [3] Thread Index in thread pool
>
> This can make for long names, e.g.:
> "TaskSchedulerBackgroudFileIOWorker3"
> but I think a descriptive name is still preferable.
>
> The one caveat is that WinDBG's implementation of thread name
> currently truncates at 32 characters... I'm willing to live with
> that for now until (if ever) we realize it's too annoying.
>
> BUG=553459
>
> Committed: https://crrev.com/a0813e0c0286ee6790433164957141e9f299bff7
> Cr-Commit-Position: refs/heads/master@{#392351}

TBR=fdoray@chromium.org,robliao@chromium.org,gab@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=553459

Review-Url: https://codereview.chromium.org/1958973003
Cr-Commit-Position: refs/heads/master@{#392364}


CrOS-Libchrome-Original-Commit: 1e27d6299d6587fec90eb89fc4ceb02e33b4023a