file_util.h won't compile if UNIT_TEST and OS_WIN are defined.
src\base/file_util.h(524) : error C2664: 'GetNamedSecurityInfoW' : cannot convert parameter 1 from 'const wchar_t *' to 'LPWSTR'

BUG=none
TEST=none

Review URL: http://codereview.chromium.org/1582040

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@45142 0039d316-1c4b-4281-b951-d872f2087c98


CrOS-Libchrome-Original-Commit: 130e036f019117d3341c2a15d06e5004e32c9501